// ---------------------------------------------------------------------------
// Shared domain types for StudyMate HSC
// ---------------------------------------------------------------------------

export type SubjectId =
  | "math-adv"
  | "math-ext1"
  | "english-adv"
  | "english-std"
  | "biology"
  | "chemistry"
  | "physics"
  | "modern-history"
  | "economics"
  | "business-studies";

export interface Subject {
  id: SubjectId;
  name: string;
  short: string;
  /** NESA learning area grouping */
  area: "Mathematics" | "English" | "Science" | "HSIE";
  /** tailwind gradient stops for the subject accent */
  gradient: [string, string];
  icon: string; // emoji/glyph used in cards
  blurb: string;
  topics: string[];
  /** how many marking bands this subject reports (most HSC = 5, some 6) */
  bands: number;
}

export type QuestionType = "multiple-choice" | "short-answer" | "extended-response";

export interface Question {
  id: string;
  subjectId: SubjectId;
  topic: string;
  type: QuestionType;
  /** total marks available */
  marks: number;
  /** the question stem (may contain line breaks) */
  prompt: string;
  /** multiple-choice options (A–D). Only for multiple-choice. */
  options?: string[];
  /** index into options for the correct answer. Only for multiple-choice. */
  correctIndex?: number;
  /** short model answer / worked solution shown after answering */
  solution: string;
  /** NESA-style marking criteria / band descriptors for written responses */
  markingCriteria?: string[];
  /** NESA syllabus outcome codes this question targets */
  outcomes?: string[];
  difficulty: "foundation" | "standard" | "challenge";
  /** true when this question was AI-generated on demand (not in the seed bank) */
  generated?: boolean;
}

// ---------- Firestore documents ----------

export interface UserProfile {
  uid: string;
  email: string;
  displayName: string;
  subjects: SubjectId[];
  premium: boolean;
  createdAt: number;
  // streak tracking
  streak: number;
  bestStreak: number;
  lastActiveDay: string | null; // yyyy-mm-dd (Australia/Sydney)
  // aggregate stats
  questionsAnswered: number;
  correctCount: number;
  onboarded: boolean;
  // gamification
  xp: number;
  /** daily goal — target questions + reviews per day */
  dailyGoal: number;
  /** badge ids earned (see lib/badges.ts) */
  badges: string[];
  // leaderboard (opt-in, anonymous alias)
  leaderboardOptIn: boolean;
  leaderboardAlias: string;
}

export interface Attempt {
  id: string;
  questionId: string;
  subjectId: SubjectId;
  topic: string;
  type: QuestionType;
  correct: boolean | null; // null for written responses that were AI-marked by band
  awardedMarks: number;
  totalMarks: number;
  createdAt: number;
}

export interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}

export interface TutorSession {
  id: string;
  subjectId: SubjectId;
  title: string;
  messages: ChatMessage[];
  createdAt: number;
  updatedAt: number;
}

// ---------- Spaced repetition (SM-2) ----------

/**
 * One reviewable item in the spaced-repetition system. Content is snapshotted
 * onto the item so the review queue renders without joins (AI-generated
 * questions and flashcards have no bank entry to look up).
 */
export interface SRSItem {
  id: string;
  kind: "question" | "flashcard";
  /** question id or `${deckId}:${cardId}` */
  refId: string;
  subjectId: SubjectId;
  topic: string;
  // snapshot content
  front: string; // question prompt or card front
  back: string; // solution or card back
  options?: string[];
  correctIndex?: number;
  // SM-2 state
  ease: number; // easiness factor, min 1.3
  interval: number; // days
  reps: number; // consecutive successful reviews
  lapses: number;
  due: string; // yyyy-mm-dd Sydney day key
  lastReviewed: number | null;
  createdAt: number;
}

/** Self-graded review quality, mapped onto SM-2's 0–5 scale. */
export type ReviewGrade = "again" | "hard" | "good" | "easy";

// ---------- Flashcards ----------

export interface Deck {
  id: string;
  name: string;
  subjectId: SubjectId;
  topic: string;
  cardCount: number;
  /** true when generated by AI rather than hand-made */
  aiGenerated: boolean;
  createdAt: number;
  updatedAt: number;
}

export interface Flashcard {
  id: string;
  front: string;
  back: string;
  createdAt: number;
}

// ---------- Daily activity (goal ring + heatmap) ----------

export interface DayStat {
  /** yyyy-mm-dd Sydney day key (doc id) */
  day: string;
  questions: number;
  reviews: number;
  essays: number;
  tutorMessages: number;
  xp: number;
}

// ---------- Exams (past paper mode) ----------

export interface ExamQuestionResult {
  questionId: string;
  topic: string;
  type: QuestionType;
  prompt: string;
  answerGiven: string;
  correct: boolean | null;
  awardedMarks: number;
  totalMarks: number;
  feedback?: string;
}

export interface ExamResult {
  id: string;
  subjectId: SubjectId;
  totalMarks: number;
  awardedMarks: number;
  durationSeconds: number;
  timeLimitSeconds: number;
  questions: ExamQuestionResult[];
  createdAt: number;
}

// ---------- Essay history ----------

export interface EssayRecord {
  id: string;
  subjectId: SubjectId;
  questionType: string;
  band: number;
  maxBand: number;
  overall: string;
  criteria: { name: string; score: number; max: number; band: number; comment: string }[];
  wordCount: number;
  createdAt: number;
}

// ---------- Study plan ----------

export interface PlanExam {
  subjectId: SubjectId;
  /** yyyy-mm-dd */
  date: string;
}

export interface PlanTask {
  subjectId: SubjectId;
  topic: string;
  activity: "practice" | "review" | "flashcards" | "essay" | "past-paper";
  minutes: number;
  note: string;
}

export interface PlanWeek {
  /** yyyy-mm-dd of the Monday starting the week */
  startDay: string;
  focus: string;
  tasks: PlanTask[];
}

export interface StudyPlan {
  exams: PlanExam[];
  hoursPerWeek: number;
  summary: string;
  weeks: PlanWeek[];
  createdAt: number;
}

// ---------- Leaderboard ----------

export interface LeaderboardEntry {
  uid: string;
  alias: string;
  xp: number;
  level: number;
  streak: number;
  updatedAt: number;
}

// ---------- AI response shapes (from /api) ----------

export interface WrittenFeedback {
  awardedMarks: number;
  totalMarks: number;
  band: number;
  maxBand: number;
  summary: string;
  strengths: string[];
  improvements: string[];
  modelPoints: string[];
}

export interface EssayFeedback {
  band: number;
  maxBand: number;
  overall: string;
  criteria: {
    name: string;
    score: number;
    max: number;
    /** estimated band this criterion sits in */
    band: number;
    comment: string;
  }[];
  nextSteps: string[];
}

export interface GeneratedQuestion {
  topic: string;
  type: QuestionType;
  marks: number;
  prompt: string;
  options?: string[];
  correctIndex?: number;
  solution: string;
  markingCriteria?: string[];
  difficulty: "foundation" | "standard" | "challenge";
}

export interface GeneratedCard {
  front: string;
  back: string;
}
